### PR TITLE
Creating embedding utils

### PR DESCRIPTION
**Pull request by callahantiff**
Created an embedding utility script and moved existing embedding functions from `Word2Vec` class to it. Specifically, the following functions are now included in this utility script:
- `get_embedding()`  
- `writes_embedding()`  
- `load_embedding()`
- `calculates_cosine_similarity()`

Please note that tests have been added for all of the above functions except `calculates_cosine_similarity()`. There is a TODO note for this in the `test_embedding_utils.py` script. I pulled the existing cosine similarity code from the `Word2Vec` implementation, but realize that this might need to be updated. It doesn't look like there are any tests for this function in the original implementation either. 

Finally, I took the opportunity to clean up some of the documentation and code to make it more closely aligned with Google Style Guidelines.

_____

This PR address issue #105.

### CODE REVIEW

**Comment by callahantiff** [comment]
> Thank you very much, Tiffany! I checked your code and ran the test_embedding_utils.py. Everything looks correct to me. Just a question, are you going to use your previous codes to calculate Katz score, Adamic-Adar, etc?

Thanks for the feedback @vidarmehr! You are referencing the script I linked

If you are OK with it, I was thinking why not! 😃  I think only minor updates would be needed in terms of the inputs and outputs, to fit with your work workflow and it is already built to be parallelized. I also have another script that post-process the output from running the code in parallel. What do you think? Happy to talk about this more!

**Related GitHub Issue:** #106

**Comment by vidarmehr** [comment]
> > Thank you very much, Tiffany! I checked your code and ran the test_embedding_utils.py. Everything looks correct to me. Just a question, are you going to use your previous codes to calculate Katz score, Adamic-Adar, etc?
> 
> Thanks for the feedback @vidarmehr! You are referencing the script I linked
> 
> If you are OK with it, I was thinking why not! 😃 I think only minor updates would be needed in terms of the inputs and outputs, to fit with your work workflow and it is already built to be parallelized. I also have another script that post-process the output from running the code in parallel. What do you think? Happy to talk about this more!
> 
> **Related GitHub Issue:** #106

Yes! That would be great! Thank you. We can also talk more on Thursday (or earlier) and see if Peter or others have any other suggestions. But, I think that we be great if you can use your codes to calculate Katz score, etc. in: https://github.com/callahantiff/owlnets/blob/master/LinkPrediction.py

**Comment by callahantiff** [comment]
> > > Thank you very much, Tiffany! I checked your code and ran the test_embedding_utils.py. Everything looks correct to me. Just a question, are you going to use your previous codes to calculate Katz score, Adamic-Adar, etc?
> > 
> > 
> > Thanks for the feedback @vidarmehr! You are referencing the script I linked
> > If you are OK with it, I was thinking why not! 😃 I think only minor updates would be needed in terms of the inputs and outputs, to fit with your work workflow and it is already built to be parallelized. I also have another script that post-process the output from running the code in parallel. What do you think? Happy to talk about this more!
> > **Related GitHub Issue:** #106
> 
> Yes! That would be great! Thank you. We can also talk more on Thursday (or earlier) and see if Peter or others have any other suggestions. But, I think that we be great if you can use your codes to calculate Katz score, etc. in: https://github.com/callahantiff/owlnets/blob/master/LinkPrediction.py

@vidarmehr  that sounds perfect! Happy to talk about it Thursday! I will also have some time to work on making a first pass at integration on Friday (or this weekend). Perhaps, if you have time, we can meet Friday morning to talk about a plan for how to best integrate the functionality you have already created with the new methods? 

Since there are so many LP algorithms, it might be easiest to do some light refactoring and organize them all in their own class. Just a thought, would love to talk about it more with you!

**Comment by vidarmehr** [comment]
> > > > Thank you very much, Tiffany! I checked your code and ran the test_embedding_utils.py. Everything looks correct to me. Just a question, are you going to use your previous codes to calculate Katz score, Adamic-Adar, etc?
> > > 
> > > 
> > > Thanks for the feedback @vidarmehr! You are referencing the script I linked
> > > If you are OK with it, I was thinking why not! 😃 I think only minor updates would be needed in terms of the inputs and outputs, to fit with your work workflow and it is already built to be parallelized. I also have another script that post-process the output from running the code in parallel. What do you think? Happy to talk about this more!
> > > **Related GitHub Issue:** #106
> > 
> > 
> > Yes! That would be great! Thank you. We can also talk more on Thursday (or earlier) and see if Peter or others have any other suggestions. But, I think that we be great if you can use your codes to calculate Katz score, etc. in: https://github.com/callahantiff/owlnets/blob/master/LinkPrediction.py
> 
> @vidarmehr that sounds perfect! Happy to talk about it Thursday! I will also have some time to work on making a first pass at integration on Friday (or this weekend). Perhaps, if you have time, we can meet Friday morning to talk about a plan for how to best integrate the functionality you have already created with the new methods?
> 
> Since there are so many LP algorithms, it might be easiest to do some light refactoring and organize them all in their own class. Just a thought, would love to talk about it more with you!

@callahantiff Sure. Greta. I can talk to you on Friday morning. Any time after 11 am (ET) works for me. Maybe 1 pm (ET)?

**Comment by callahantiff** [comment]
> > > > > Thank you very much, Tiffany! I checked your code and ran the test_embedding_utils.py. Everything looks correct to me. Just a question, are you going to use your previous codes to calculate Katz score, Adamic-Adar, etc?
> > > > 
> > > > 
> > > > Thanks for the feedback @vidarmehr! You are referencing the script I linked
> > > > If you are OK with it, I was thinking why not! 😃 I think only minor updates would be needed in terms of the inputs and outputs, to fit with your work workflow and it is already built to be parallelized. I also have another script that post-process the output from running the code in parallel. What do you think? Happy to talk about this more!
> > > > **Related GitHub Issue:** #106
> > > 
> > > 
> > > Yes! That would be great! Thank you. We can also talk more on Thursday (or earlier) and see if Peter or others have any other suggestions. But, I think that we be great if you can use your codes to calculate Katz score, etc. in: https://github.com/callahantiff/owlnets/blob/master/LinkPrediction.py
> > 
> > 
> > @vidarmehr that sounds perfect! Happy to talk about it Thursday! I will also have some time to work on making a first pass at integration on Friday (or this weekend). Perhaps, if you have time, we can meet Friday morning to talk about a plan for how to best integrate the functionality you have already created with the new methods?
> > Since there are so many LP algorithms, it might be easiest to do some light refactoring and organize them all in their own class. Just a thought, would love to talk about it more with you!
> 
> @callahantiff Sure. Great. I can talk to you on Friday morning. Any time after 11 am (ET) works for me. Maybe 1 pm (ET)?

OK, let's do Friday at 1pm ET. I will send you a calendar invite!

**Comment by vidarmehr** [comment]
@pnrobinson @callahantiff 
I think we can merge this branch to develop. Peter, would you please take a look at this branch and approve pull request, if you agree? Thank you.

**Comment by callahantiff** [comment]
> prepare_lables_test_training

@pnrobinson - It looks like the typo is occurring in `link_predition.py` script. I assume it is OK for me to fix this

**Comment by callahantiff** [comment]
@pnrobinson , @vidarmehr - merge conflicts resolved and tests now passing. Should I proceed with merging?

**Comment by pnrobinson** [comment]
Please do the honors!

**Pull request merged**
