### PR TITLE
Update code to support heterogenous graphs

### PR DESCRIPTION
**Pull request by justaddcoffee**
Update `__preprocess_transition_probs_xn2v()` to use indexes instead of strings for keys, per convo with Vida

@vidarmehr I think this is what needs to be done to get heterogenous graph support working (feel free to edit PR or suggest changes)

### CODE REVIEW

**Comment by vidarmehr** [comment]
Yes, Justin! __preprocess_transition_probs_xn2v() needs to be updated. Also, some tests in test_hetnode2vec fail. I have commented them out for now. But, I think there is an issue in get_alias_edge_xn2v(self, src, dst)

The tests that fail are:
test_raw_probs_2 and test_raw_probs_simple_graph_2. 

I would appreciate it if you can help me with these issues. Thank you.

**Comment by justaddcoffee** [comment]
Okay, I see the tests you mean - I'll try and fix them, but feel free to push to this branch if you feel like fixing them before that

**Comment by justaddcoffee** [comment]
Update - I spent some time tonight and:
- refactored the tests a lot, to DRY them out and make them a little faster. 
- renamed things for clarity
- uncommented and `@skip`'d the 2 failing tests

I'll hopefully fix the 2 failing tests tomorrow

**Comment by vidarmehr** [comment]
@justaddcoffee @pnrobinson 
Dear Justin and Peter, I have modified the hetnode2vec.py and tested the probabilities of going from one node to another node. I still use the node names and not their indices. But, I will work on it. I think the changes would be similar to what Justin had done it before. If you agree, I think it is better if we close this pull request. I create another pull request and merge this branch to develop. Please let me know if you have a comment or suggestion. Thank you.

**Comment by pnrobinson** [comment]
Why is this line failing in travis?
```
The command "nosetests --with-coverage --cover-package=xn2v --cover-xml" exited with 1.
```
It seems all of the unit tests are being passed?

**Comment by vidarmehr** [comment]
> Why is this line failing in travis?
> 
> ```
> The command "nosetests --with-coverage --cover-package=xn2v --cover-xml" exited with 1.
> ```
> 
> It seems all of the unit tests are being passed?

I found the issue. I fix it quickly.

**Comment by vidarmehr** [comment]
@pnrobinson All checks have passed. Can I merge it?

**Pull request merged**
