### PR TITLE
Parallelize random walks

### PR DESCRIPTION
**Pull request by justaddcoffee**
Should shave off a little runtime

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@vidarmehr could you try this out with a short run?

**Comment by vidarmehr** [comment]
@justaddcoffee Sure. I will run the code tonight.

**Comment by vidarmehr** [comment]
@justaddcoffee 
I am trying to run the code, but I get the error:

> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 2, in <module>
    from xn2v import CSFGraph
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/__init__.py", line 9, in <module>
    from .hetnode2vec import N2vGraph
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/hetnode2vec.py", line 11, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'

I installed tqdm using 
`pip3 install tqdm`
or with pycharm ->preferences-> project interpreter,  but again I am receiving this message! Do you know what the problem is? Thank you.

**Comment by vidarmehr** [comment]
@justaddcoffee and @LucaCappelletti94 

I solved the issue. Sorry. I had installed tqdm in the correct environment that I had created for this project, but project interpreter was not the correct one.
So, the link prediction code runs successfully on my machine.

**Comment by justaddcoffee** [comment]
+1

**Pull request merged**
