### PR TITLE
Small refactorings to make code more pythonic

### PR DESCRIPTION
**Pull request by LucaCappelletti94**

### CODE REVIEW

**Comment by LucaCappelletti94** [comment]
I get a couple of errors from Travis which does not seem related to my commits, I think a couple of files are missing: `TypeError: Could not find graph file data/ppismall/pos_train_edges` and  `TypeError: Could not find graph file data/ppismall/pos_train_edges`.

**Comment by callahantiff** [comment]
@LucaCappelletti94 - Sorry you are getting an error! This file has definitely had some significant changes made to it on the `creating_keras_develop_branch` branch, which has not yet been merged with other branches. Our thought being to make one giant PR from this branch when we had finished the full `tf` refactor. I'm now wondering if it might be worth it to make a branch of `creating_keras_develop_branch` and push some of the intermediate changes to files that are not dependent on the `tf` refactor.

What do you think about this? Sorry for the headache caused by these errors!

**Comment by justaddcoffee** [comment]
@LucaCappelletti94 I think this should fix the problematic test here

**Comment by justaddcoffee** [comment]
@LucaCappelletti94 I changed the base to `develop` (from `master`) - since generally we want to merge into `develop`

if there are no objections, it would also be helpful to make PRs from named branches (e.g. `my_awesome_pr`) on https://github.com/monarch-initiative/N2V instead of our individual forks of N2V (not strictly necessary though)

**Comment by callahantiff** [comment]
@justaddcoffee - what did you think about my comment above?

**Comment by justaddcoffee** [comment]
> @justaddcoffee - what did you think about my comment above?

Could we chat about how to do this? Possibly could just cherry-pick some commits from `creating_keras_develop_branch` into `develop`. Or possibly it might be simplest to just finish the tf refactor as soon as possible and then deal with all the differences between these two branches.

**Comment by callahantiff** [comment]
> > @justaddcoffee - what did you think about my comment above?
> 
> Could we chat about how to do this? Possibly could just cherry-pick some commits from creating_keras_develop_branch into develop. Or possibly it might be simplest to just finish the tf refactor as soon as possible and then deal with all the differences between these two branches.

Happy to do whatever is easiest, just thought it was worth mentioning. Either way, I'm happy to approve this PR once the merge conflicts are resolved.

**Comment by justaddcoffee** [comment]
This is going to be hard to merge since it's based on `master` not `develop` - without any objection, I'm going to make a new PR for this and put Luca's nice improvements in that

**Pull request closed without merging**
