### PR TITLE
Linkprediction functions

### PR DESCRIPTION
**Pull request by vidarmehr**
@callahantiff Hi Tiffany, I have added some link prediction functions (Degree Product, Common Neighbors,Jaccard's score, Adamic Adar score and cosine similarity score) to link_prediction_functions.py and have done tests on these functions in test_link_prediction_functions.py. Please let me know if you see any issues. Thaks.

### CODE REVIEW

**Comment by callahantiff** [comment]
@vidarmehr - Awesome job on this!! Will I hold you back on anything if I check this later today/this evening?

**Comment by vidarmehr** [comment]
> @vidarmehr - Awesome job on this!! Will I hold you back on anything if I check this later today/this evening?

Thanks, Tiffany! No. Take your time. I want to work on issues that Peter has mentioned.

**Comment by callahantiff** [comment]
Would you like me to merge @vidarmehr or did you want the honor? 😃

**Comment by vidarmehr** [comment]
> Would you like me to merge @vidarmehr or did you want the honor? 😃

Thank you very much, Tiffany! Please merge the branch to develop :-)

**Comment by callahantiff** [comment]
@vidarmehr - just a heads up, Travis was failing due to a bunch of typing errors, which for all the scripts except `word2vec.py` were very trivial. The typing errors in the `word2vec.py` have been temporarily silenced so that we can get this stuff merged, but I want to mention that many of the issues that mypy pointed out will need additional review/TLC downstream. Just wanted to make sure that I let you know. 😄 

OK, merging and deleting the branch now!

**Comment by vidarmehr** [comment]
> @vidarmehr - just a heads up, Travis was failing due to a bunch of typing errors, which for all the scripts except `word2vec.py` were very trivial. The typing errors in the `word2vec.py` have been temporarily silenced so that we can get this stuff merged, but I want to mention that many of the issues that mypy pointed out will need additional review/TLC downstream. Just wanted to make sure that I let you know. 😄
> 
> OK, merging and deleting the branch now!

Ok. Thanks a lot, Tiffany!

**Pull request merged**
