### PR TITLE
Neural networks

### PR DESCRIPTION
**Pull request by LucaCappelletti94**
I have added three neural network models: an MLP, a FFNN and a multi-modal FFNN. The first two receive in input the edges vectors, while the multi-modal one receives the two vectors for each node.

I have integrated MLP and FFNN in the link prediction, but I don't know where to integrate the multi-modal one.

These models are a proposal as it is very hard to say that one is definitely the best one. Especially for the multi-modal network, it could be possible to add some l2 activity regularization on the layers close to the input.

### CODE REVIEW

**Comment by vidarmehr** [comment]
@LucaCappelletti94 
Thank you, Luca! I ran the code using MLP classifier and I got the error:

> Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 221, in <module>
    main(args)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 216, in main
    linkpred(pos_train_graph, pos_valid_graph, pos_test_graph, neg_train_graph, neg_valid_graph, neg_test_graph)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 162, in linkpred
    lp.predict_links()
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/link_prediction.py", line 165, in predict_links
    edge_classifier.fit(self.train_edge_embs, self.train_edge_labels)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/neural_networks.py", line 115, in fit
    TQDMNotebookCallback() if is_notebook() else TQDMCallback()
TypeError: fit() got multiple values for argument 'epochs'

I think the code needs some debugging before merging this branch to develop.

**Comment by LucaCappelletti94** [comment]
Hi @vidarmehr! Could you add the test you have used to execute the pipeline in the tests folder? It would help me out quite a bit.

**Comment by LucaCappelletti94** [comment]
@vidarmehr could you rerun your test? Thank you!

**Comment by vidarmehr** [comment]
> @vidarmehr could you rerun your test? Thank you!

@LucaCappelletti94 I use the command:
python runLinkPrediction_ppi.py --classifier MLP

Now, I got this error message:
Traceback (most recent call last):
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 221, in <module>
    main(args)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 216, in main
    linkpred(pos_train_graph, pos_valid_graph, pos_test_graph, neg_train_graph, neg_valid_graph, neg_test_graph)
  File "/Users/ravanv/PycharmProjects/N2V/runLinkPrediction_ppi.py", line 162, in linkpred
    lp.predict_links()
Finished ingesting 100 lines (vectors) from embedded_graph.embedded
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/link_prediction.py", line 165, in predict_links
    edge_classifier.fit(self.train_edge_embs, self.train_edge_labels)
  File "/Users/ravanv/PycharmProjects/N2V/xn2v/neural_networks.py", line 120, in fit
    TQDMNotebookCallback() if is_notebook() else TQDMCallback()
  File "/Users/ravanv/anaconda3/envs/N2V-TF/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 704, in fit
    raise TypeError('Unrecognized keyword arguments: ' + str(kwargs))
TypeError: Unrecognized keyword arguments: {'validation': None}

**Comment by justaddcoffee** [comment]
Hi @LucaCappelletti94 - can I push a commit with a type hint to fix that mypy error?

**Comment by LucaCappelletti94** [comment]
> Hi @LucaCappelletti94 - can I push a commit with a type hint to fix that mypy error?

By all means! Thank you!

**Comment by justaddcoffee** [comment]
> By all means! Thank you!

NP @LucaCappelletti94 !

**Comment by LucaCappelletti94** [comment]
Should we add a test to run a link prediction with the possible models, so to increase the coverage?

**Comment by vidarmehr** [comment]
> Should we add a test to run a link prediction with the possible models, so to increase the coverage?

Yeah, I thin that should be a good idea. I am trying to find why some checks fail.

**Comment by justaddcoffee** [comment]
> Should we add a test to run a link prediction with the possible models, so to increase the coverage?

Yeah, good idea! 

Also, I think I see how to implement multi-modal FFNN here - should I have a go at this and push to this branch?

**Comment by vidarmehr** [comment]
> > Should we add a test to run a link prediction with the possible models, so to increase the coverage?
> 
> Yeah, good idea!
> 
> Also, I think I see how to implement multi-modal FFNN here - should I have a go at this and push to this branch?

Yes, Please. Thank you Justin!

**Comment by justaddcoffee** [comment]
> Yes, Please. Thank you Justin!

great - give me an hour or so

**Comment by vidarmehr** [comment]
> > Yes, Please. Thank you Justin!
> 
> great - give me an hour or so

Sure. No worries. Take your time. Meanwhile, I work on the manuscript.

**Comment by LucaCappelletti94** [comment]
> > Should we add a test to run a link prediction with the possible models, so to increase the coverage?
> 
> Yeah, good idea!
> 
> Also, I think I see how to implement multi-modal FFNN here - should I have a go at this and push to this branch?

The multi-modal model is already implemented, there is only the need to provide the correct training data. If you like I'm up for a quick Zoom call.

**Comment by justaddcoffee** [comment]
> The multi-modal model is already implemented, there is only the need to provide the correct training data. If you like I'm up for a quick Zoom call.

Yeah, I noticed that you already implemented this - I meant I see how to provide multimodelFFNN the correct data. 

I can zoom now if you are around - might go faster if we pair programmed this

**Comment by vidarmehr** [comment]
@justaddcoffee @LucaCappelletti94 Dear Justin and Luca, Would you please merge this branch  to develop when you are done? Thanks.

**Comment by callahantiff** [comment]
Sorry I'm late to the party on this (and for missing the meeting yesterday). This addition looks awesome. I can't wait to use it!

**Pull request merged**
