### PR TITLE
Glove

### PR DESCRIPTION
**Pull request by pnrobinson**
Working on porting tf1 GloVe implementation to tf2 (not working yet but just a separate file). Not requesting a detailed review at this point, but please look at this and if anybody can figure out what is not working, please shout. Note you need to provide some text as input. I downloaded a Dickens novel from project Gutenberg
```
AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute '_in_graph_mode'
```

### CODE REVIEW

**Comment by justaddcoffee** [comment]
> I think this is OK, it corrects a few bugs but mainly is one additional file

Okay, no problem - we can incorporate this after the keras refactor

**Comment by pnrobinson** [comment]
Everything is now integrated, and SG and CBOW work on small test cases with the new refactor. We will be doing some more realistic tests with the code on the JAX cluster, so we can see if the keras does better or worse! But no more refactoring for now.

**Comment by callahantiff** [comment]
This is awesome @pnrobinson! I'm so excited to start using this stuff.

@justaddcoffee, I added [this](https://github.com/monarch-initiative/N2V/projects/1#card-33154524) project card for incorporating the referenced GloVe code.

**Comment by justaddcoffee** [comment]
> @justaddcoffee, I added this project card for incorporating the referenced GloVe code.

+1

**Pull request merged**
