### PR TITLE
Better support node types

### PR DESCRIPTION
**Pull request by justaddcoffee**
To address #104 and #26

- Per ticket #104, this PR will change `CSFGraph` and other classes so that edges are read from a [KGX-style TSV file](https://github.com/NCATS-Tangerine/kgx/blob/master/data-preparation.md) with these columns: 
`subject    edge_label    object    relation`
And a node TSV file with these columns:
`id     name    category`

- a node type for each node will be assigned using the `category` column in the node TSV file

- alter the random walk logic so that it uses node type to inform the random walk (if gamma parameter is being used)

- I've also altered the `Edge` class so that it has an `edge_type` attribute that is populated using the `edge_label` column of the edge TSV file

- I've made an effort to be backward-compatible with "legacy" edge files like the following, with no header, and 3 columns: node1, node2 and weight:
`node1  node2  10.1`
these should still work as long as they are TSVs

- I've added lots of unit tests for the new code, and some tests for existing code too

### CODE REVIEW

**Comment by justaddcoffee** [comment]
@pnrobinson could you spare some time tomorrow to walk through this briefly?

**Comment by pnrobinson** [comment]
@justaddcoffee  Possibly tomorrow at 12noon or (less good) 10 AM Eastern?

**Comment by justaddcoffee** [comment]
> @justaddcoffee Possibly tomorrow at 12noon or (less good) 10 AM Eastern?

@pnrobinson Sure, let's shoot for 12 noon Eastern

**Comment by justaddcoffee** [comment]
@pnrobinson per our convo, the commit I just added causes 3 het graph tests to fail when I rename p1 to a gene CURIE ("NCBIGene:12345" or some such)

See for example this test:
`    def test_raw_probs_simple_graph_1(self):`

**Comment by justaddcoffee** [comment]
@pnrobinson I think I see why this test is failing - the probabilities are being calculated correctly[here](https://github.com/monarch-initiative/N2V/blob/e79193b65d785a1af60933b381ce3bceaac78e39/tests/test_hetnode2vec_tf.py#L39), it's just that the order of sorted neighbors has changes since `p1` is now `UniprotKB:1234`. 

Before the neighbors of 'g1' were: 
`['g1', 'g3', 'p1', 'p2']`
and the probabilities were:
`[0.25       0.25       0.33333333 0.16666667]`

Now the neighbors are:
`['UniprotKB:1234', 'g1', 'g3', 'p2']`
and the probabilities are:
`[0.33333333 0.25       0.25       0.16666667]`

**Comment by justaddcoffee** [comment]
@pnrobinson @vidarmehr @callahantiff could you have a look at the [parameterized tests I just pushed](https://github.com/monarch-initiative/N2V/blob/b10b563f03a937735728150d3cc74f393d65cc35/tests/test_hetnode2vec_tf.py#L26)? Compare with [here lines 16 - 125](https://github.com/monarch-initiative/N2V/blob/ccaf7de049ee57d1d93ab806158bccc222ed9ea8/tests/test_hetnode2vec_tf.py#L16)

I think these are easier to read and maybe less brittle. If you like these and are okay with them, I'll refactor the other tests in `test_hetnode2vec_tf.py`, but if not I'll hold my horses - the previous tests were fine too.

**Comment by pnrobinson** [comment]
Nice--I hadn't seen the parameterized tests before but that is a lot nicer than many individual tests

**Comment by pnrobinson** [comment]
I will go ahead and merge -- let's continue to test this as we work with het. graphs!

**Comment by justaddcoffee** [comment]
Great! Thanks @pnrobinson

**Pull request merged**
